index.js, package.json, spec/create.spec.js, spec/helpers.js
This PR does a lot of overdue house keeping. Removing dead code, factoring out repeated patterns, fixing some comments and other cleanup tasks.
I intentionally kept the commits separate for now because I think this rather big change set is more reviewable this way. If it is preferred, the commits can still be squashed in the end.
*Fix error shadowing on failed fetch* fixes an error that was thrown while handling another error.
None of the other commits should introduce any change in behavior.
The test duration was brought down to about half a second (was more than a minute sometimes) by mocking out any calls to `fetch`.
I'm looking forward to your feedback. I hope you are with me on this PR. I made a few breaking changes locally that I would like to build onto this.
``` …
```
=> Major code cleanup

spec/helpers.js
The message in case of failure was negated.
=> Fix error messages for toExist matcher

spec/create.spec.js, spec/templates/config_in_www/www/config.xml, spec/templates/no_content_config.xml, spec/templates/nopackage_json/config.xml, spec/templates/withpackage_json/config.xml, spec/templates/withsubdirectory/template/config.xml, spec/templates/withsubdirectory_package_json/template/config.xml
This builds on top and further improves upon the great test cleanup done by @brodybits in #14. Due to #8 being blocked for now, I removed all related changes in the hopes that we can merge the remaining changes ASAP.
If you want to compare this with the original changes by @brodybits, compare against the second commit 
5f0d79e. Everything after that is new.
I left the commits separate so the whole thing is easier to review. We can squash all of this on merge.
=> Cleanup tests

index.js, package.json
Resolves §2 from apache/cordova-discuss/issues/89
=> Drop support for reading from .cordova/config.json

index.js, package.json, spec/create.spec.js
=> Further non-breaking cleanup & improvements

spec/templates/withsubdirectory_package_json/template/package.json
none
Updates the license of a test spec's `package.json` from Apache-1.0 to Apache-2.0.
**Changes**
`"license": "Apache-1.0",` becomes `"license": "Apache-2.0",`
- `npm i`
- `npm run jasmine`
=> Updated Apache License Version

package-lock.json, package.json
Use current version of `nyc` to resolve a bug that was seen with v13.x on Windows with node >= 10.
Update `nyc` dev dependency
=> chore: update nyc dev dependency

package-lock.json
This is to remove noise in the dependabot PRs.
http URLs were originally caused by a [npm registry issue](https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285/50).
=> Replace http URLs in package-lock.json w/ https

package-lock.json, package.json
Update the third-party production npm dependencies to ensure that our package remains vulnerability free that can come from third-party dependencies.
Enables us to use new features, leverage speed improvements, and resolve issues that were caused by third-party dependency bugs.
Updated Dependencies
* fs-extra@^8.1.0
* import-fresh@^3.1.0
* isobject@^4.0.0
* tmp@^0.1.0
- `npm t`
=> chore: bump production dependencies

package-lock.json, package.json, spec/support/jasmine.json
Keep the testing tools updated.
Bump the `jasmine` dependency and updated `nyc` configs.
- `npm t`
=> chore: update testing (jasmine & nyc)

index.js, package-lock.json, package.json, spec/create.spec.js
Fixes #34 
We use `npm-package-arg` to determine to what a spec refers. That's the package used by `npm` for spec parsing.
Added unit tests before the change, including one failing for #34. Tests all pass after change.
=> Fix isRemoteUri

.eslintignore, .eslintrc.yml, package-lock.json, package.json, spec/.eslintrc.yml, spec/create.spec.js, spec/helpers.js
* replace eslint dependencies with @cordova/eslint-config
* update eslint config
* eslint corrections
- `npm t`
=> refactor: eslint setup

index.js, package-lock.json, package.json, spec/create.spec.js
It is impossible to deploy `.gitignore` files via npm packages.
Instead, Cordova templates should include `gitignore` files that we
rename to `.gitignore`. This PR implements that renaming.
For more details see apache/cordova-discuss#69.
Closes #8, apache/cordova-app-hello-world#30 and apache/cordova-discuss#69.
This bumps the dependency on `cordova-app-hello-world` to a version that includes apache/cordova-app-hello-world#50.
Rename all `gitignore` files in the generated app to `.gitignore`.
_Note_: Originally we had discussed using the filename `_gitignore` for the source files but I eventually went with what `create-react-app` [is using in their templates](https://github.com/facebook/create-react-app/blob/4c0c81953d090dbf122e126f2b6b8c803d4a0569/packages/react-scripts/scripts/init.js#L1 …
=> feat: support .gitignore files in generated app

.eslintrc.yml, spec/.eslintrc.yml
Consolidate configs into one file
* Removed `.eslintrc.yml` from testing directory and added configs to parent configs as override.
* Added missing Apache Header License
- `npm t`
=> chore: eslint config cleanup

package-lock.json, package.json
Use latest Cordova ESLint rules
Merge order: #58 → #59
- `npm t`
=> chore(eslint): bump package

index.js, spec/create.spec.js, spec/helpers.js, spec/templates/withsubdirectory/index.js, spec/templates/withsubdirectory_package_json/index.js
* Modernizing Syntax
* `var` to `let` & `const`
* `arrow` functions
- `npm t`
=> refactor: small syntax changes

package-lock.json, package.json
This PR updates all release and dev dependencies & converts the package-lock.json to v2.
**Update Release Dependencies:**
* `cordova-app-hello-world@^6.0.0`
* `cordova-common@^4.0.2`
* `cordova-fetch@^3.0.1`
* `fs-extra@^10.0.0`
* `globby@^11.0.4`
* `import-fresh@^3.3.0`
* `npm-package-arg@^8.1.5`
**Update Dev Dependencies:**
* `@cordova/eslint-config@^4.0.0`
* `jasmine@^3.10.0`
* `nyc@^15.1.0`
**Update Exception:**
* `globby` is only bumped to the latest version in the 11.x series. It current latest major series, 12.x, only supports ESM which Cordova does not support.
- `npm t`
=> dep!: update all dependencies

.github/workflows/ci.yml
n/a
* Drop deprecatetd node version 
* Add latettst node versions
* Update GH Action dependencies
* Drop node 10 & 12
* Add node 16 & 18
* Bump Action Deps.
* `actions/checkout@v3`
* `actions/setup-node@v3`
* `codecov/codecov-action@v3`
n/a
=> ci(workflow): update node support & action dependencies

.github/workflows/ci.yml, index.js, package-lock.json, package.json, spec/create.spec.js, spec/helpers.js
All
Update some dependencies.
* Add node 20 to CI
* Update GitHub Actions dependencies
* Rebuild package-lock to resolve npm audit warnings
* Replace `fs-extra` dependency with Node core `fs` API
Unit tests pass.
=> chore(deps): Update npm deps, add Node 20 to CI

.github/workflows/ci.yml, package-lock.json, package.json, spec/create.spec.js
n/a
node < 20 are already EOL.
- Upgrade node to 20.5.0
- Bump node modules:
- cordova-common
- import-fresh
- npm-package-arg
- tmp
- @cordova/eslint-config
- jasmine
- nyc
- rewire
- Update test due to bump `npm-package-arg`
- Update packages by npm update
NOTE:
- `tmp` is updated only in package.json. Before this change, already use 0.2.3 in package-lock.json.
- `globby` could not be updated because it switched commonjs to esm from next version.
- `nyc` should be replaced with `c8` but separate from this PR.
- npm t
- npm lint
=> chore!: bump node requirement & npm dependencies
